Fix compilation error with ARMv5 atomics when T is a const value.
Error was:
../../include/QtCore/../../src/corelib/arch/qatomic_armv5.h:301: error:
invalid conversion from 'const void*' to 'void*'

faba550d704312a29d9485bcaaa506331f102301 introduced the fix to 4.7,
but since the file was renamed in 4.8, the merge didn't apply. The
conflict resolution in 91efdcae was incomplete.

Reviewed-by: Harald Fernengel