Fix compilation: StringImpl has no public, default constructor
Error was:
platform/text/AtomicStringImpl.h:29: error: base `WebCore::StringImpl' with only non-default constructor in class without a constructor

Reviewed-by: Janne Koskinen
(cherry picked from commit 42bbbfb3cd36a935d30e7f49f87ab8d7f1d2b53e)