Fix compilation by s/intptr_t/quintptr/
intptr_t is defined in some C header that we don't include. I don't
know which one it is, but without it, it fails to compile with:

declarative/qml/qdeclarativecontext.cpp:477: error: 'intptr_t' was not declared in this scope

Reviewed-By: Trust Me