Fixed compile of scripttools with MSVC 2003.
Fixes compile error:
  debugging\qscriptdebuggercommand.cpp(567) : error C2664: 'QScriptDebuggerCommand::setAttribute' : cannot convert parameter 2 from 'const QStringList' to 'const QVariant &'
          Reason: cannot convert from 'const QStringList' to 'const QVariant'
          Source or target has incomplete type