Fix broken test on windows
stringbuilder.cpp(160) : error C2666: 'operator +' : 2 overloads have similar conversions
stringbuilder.h(416): could be 'QStringBuilder<A,B> operator +<QByteArray,char[5]>(const A &,const B (&))'
            with
            [
                A=QByteArray,
                B=char [5]
            ]
            or       'built-in C++ operator+(__int64, char [5])'
            while trying to match the argument list '(QByteArray, char [5])'

The reason is the cast to QNoImplicitBoolCast (which is int)