Fix SSSE3 support build failure on mingw
Commit 94253f3472a13ac4eab3ccfbbba9d14165647f85 made QMAKE_MAC_XARCH
to be set to 'no' for MinGW environments. Due to this change building
for MinGW environments where SSSE3 support is available got broken.
While building the imageformats plugin qjpeg4 the following error occurs:

undefined reference to `_imp___Z32qt_convert_rgb888_to_rgb32_ssse3PjPKhi'

This commit makes building Qt on MinGW environments where SSSE3 support
is available working again

Change-Id: Ib2a4b3cc244af8bdde70d2d2240c70ff0e7a4cc2
Reviewed-by: Andy Shaw <andy.shaw@digia.com>
Reviewed-by: Daniel Molkentin <daniel@molkentin.de>