Revert "don't include uic in non-gui configurations"
This reverts commit 7d2c8eb99c563b4fb236fe538123255f52f293a2.

This commit was not reviewed and breaks compile of QtNetwork on win32
with this error...

 src\network\kernel\qauthenticator.cpp(55) : fatal error C1083: Cannot
 open include file: '../3rdparty/des/des.cpp': No such file or
 directory

... because the generated Makefile no longer contains src/network
as an include path.