Fix C++11 narrowing error.
src/opengl/qgl_x11.cpp:1805:21: error: non-constant-expression cannot be
narrowed from type 'unsigned int' to 'int' in initializer list
[-Wc++11-narrowing]
  0x20D4, options & QGLContext::CanFlipNativePixmapBindOption ? 0xFFFFFFFF : 0,

Simply add an explicit cast to the expression to make it build with libc++.

No cherry-pick, this file does not exist in qt5.

Change-Id: Ic2fc636fc21a87dae848c062acb048e4a623a1f2
Reviewed-by: Samuel Rødal <samuel.rodal@digia.com>