Add the parameter to the function call.
Apparently we have a problem with these default parameters. We have
basically:

template<typename T> void func(T * = 0);
template<> void func<Something>(Something *);

Now, according to GCC, I can't add "= 0" to the template
specialisation. However, MSVC 2008 isn't able to call the
specialisation without my extra 0 here. I've seen a similar issue
before in QSharedPointer.

I don't think this is a big deal because the error message output by
MSVC 2008 indicates this is likely a compiler bug:

qdbuspendingreply.h(98) : error C2440: 'default argument': cannot
convert from 'T1 *' to 'QVariant *'
where
    [
	T1=QVariant
    ]