Revert "Removed double setting of _WIN32_WINNT"
This reverts commit a165d1cfbb15ced6079a0d752fbdb37a478ff46f.

Was causing an error: (msvc2005)
qthread_win.cpp(369) : error C3861: 'SwitchToThread': identifier not found