Fix compilation with Sun CC 5.9: ambiguity in ?:
Error: Ambiguous "?:" expression, second operand of type "WTF::PassRefPtr<WebCore::DocumentFragment>" and third operand of type "int" can be converted to one another.
Error: Ambiguous "?:" expression, second operand of type "WTF::PassRefPtr<JSC::Label>" and third operand of type "int" can be converted to one another.
[and others similar]

Conflicts:

	src/3rdparty/webkit/WebCore/workers/WorkerContext.cpp