QSslError: Actually make strings show up in the ts file
I suspect because of missing quotation marks those strings were not
showing up. Also, wrapping QT_TRANSLATE_NOOP inside a tr() call
makes no sense. Also changed the class from QObject to QSslSocket.

Task-number: QTBUG-5059
Reviewed-by: ossi